// Code generated by MockGen. DO NOT EDIT.
// Source: helloworld-ai/internal/vectorstore (interfaces: VectorStore)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_vector_store.go -package=mocks helloworld-ai/internal/vectorstore VectorStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	vectorstore "helloworld-ai/internal/vectorstore"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockVectorStore is a mock of VectorStore interface.
type MockVectorStore struct {
	ctrl     *gomock.Controller
	recorder *MockVectorStoreMockRecorder
	isgomock struct{}
}

// MockVectorStoreMockRecorder is the mock recorder for MockVectorStore.
type MockVectorStoreMockRecorder struct {
	mock *MockVectorStore
}

// NewMockVectorStore creates a new mock instance.
func NewMockVectorStore(ctrl *gomock.Controller) *MockVectorStore {
	mock := &MockVectorStore{ctrl: ctrl}
	mock.recorder = &MockVectorStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVectorStore) EXPECT() *MockVectorStoreMockRecorder {
	return m.recorder
}

// CollectionExists mocks base method.
func (m *MockVectorStore) CollectionExists(ctx context.Context, collection string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CollectionExists", ctx, collection)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CollectionExists indicates an expected call of CollectionExists.
func (mr *MockVectorStoreMockRecorder) CollectionExists(ctx, collection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectionExists", reflect.TypeOf((*MockVectorStore)(nil).CollectionExists), ctx, collection)
}

// Delete mocks base method.
func (m *MockVectorStore) Delete(ctx context.Context, collection string, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, collection, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockVectorStoreMockRecorder) Delete(ctx, collection, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVectorStore)(nil).Delete), ctx, collection, ids)
}

// Search mocks base method.
func (m *MockVectorStore) Search(ctx context.Context, collection string, query []float32, k int, filters map[string]any) ([]vectorstore.SearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, collection, query, k, filters)
	ret0, _ := ret[0].([]vectorstore.SearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockVectorStoreMockRecorder) Search(ctx, collection, query, k, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockVectorStore)(nil).Search), ctx, collection, query, k, filters)
}

// Upsert mocks base method.
func (m *MockVectorStore) Upsert(ctx context.Context, collection string, points []vectorstore.Point) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, collection, points)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockVectorStoreMockRecorder) Upsert(ctx, collection, points any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockVectorStore)(nil).Upsert), ctx, collection, points)
}
