// Code generated by MockGen. DO NOT EDIT.
// Source: helloworld-ai/internal/service (interfaces: LLMClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_llm_client.go -package=mocks helloworld-ai/internal/service LLMClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLLMClient is a mock of LLMClient interface.
type MockLLMClient struct {
	ctrl     *gomock.Controller
	recorder *MockLLMClientMockRecorder
	isgomock struct{}
}

// MockLLMClientMockRecorder is the mock recorder for MockLLMClient.
type MockLLMClientMockRecorder struct {
	mock *MockLLMClient
}

// NewMockLLMClient creates a new mock instance.
func NewMockLLMClient(ctrl *gomock.Controller) *MockLLMClient {
	mock := &MockLLMClient{ctrl: ctrl}
	mock.recorder = &MockLLMClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMClient) EXPECT() *MockLLMClientMockRecorder {
	return m.recorder
}

// Chat mocks base method.
func (m *MockLLMClient) Chat(ctx context.Context, message string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chat", ctx, message)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Chat indicates an expected call of Chat.
func (mr *MockLLMClientMockRecorder) Chat(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chat", reflect.TypeOf((*MockLLMClient)(nil).Chat), ctx, message)
}

// StreamChat mocks base method.
func (m *MockLLMClient) StreamChat(ctx context.Context, message string, callback func(string) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamChat", ctx, message, callback)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamChat indicates an expected call of StreamChat.
func (mr *MockLLMClientMockRecorder) StreamChat(ctx, message, callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamChat", reflect.TypeOf((*MockLLMClient)(nil).StreamChat), ctx, message, callback)
}
