// Code generated by MockGen. DO NOT EDIT.
// Source: helloworld-ai/internal/service (interfaces: ChatService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_chat_service.go -package=mocks -mock_names=ChatService=MockChatService helloworld-ai/internal/service ChatService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	service "helloworld-ai/internal/service"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockChatService is a mock of ChatService interface.
type MockChatService struct {
	ctrl     *gomock.Controller
	recorder *MockChatServiceMockRecorder
	isgomock struct{}
}

// MockChatServiceMockRecorder is the mock recorder for MockChatService.
type MockChatServiceMockRecorder struct {
	mock *MockChatService
}

// NewMockChatService creates a new mock instance.
func NewMockChatService(ctrl *gomock.Controller) *MockChatService {
	mock := &MockChatService{ctrl: ctrl}
	mock.recorder = &MockChatServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatService) EXPECT() *MockChatServiceMockRecorder {
	return m.recorder
}

// ProcessChat mocks base method.
func (m *MockChatService) ProcessChat(ctx context.Context, req service.ChatRequest) (service.ChatResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessChat", ctx, req)
	ret0, _ := ret[0].(service.ChatResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessChat indicates an expected call of ProcessChat.
func (mr *MockChatServiceMockRecorder) ProcessChat(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessChat", reflect.TypeOf((*MockChatService)(nil).ProcessChat), ctx, req)
}

// StreamChat mocks base method.
func (m *MockChatService) StreamChat(ctx context.Context, req service.ChatRequest, callback func(string) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamChat", ctx, req, callback)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamChat indicates an expected call of StreamChat.
func (mr *MockChatServiceMockRecorder) StreamChat(ctx, req, callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamChat", reflect.TypeOf((*MockChatService)(nil).StreamChat), ctx, req, callback)
}
