// Code generated by MockGen. DO NOT EDIT.
// Source: helloworld-ai/internal/storage (interfaces: NoteStore)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_note_store.go -package=mocks helloworld-ai/internal/storage NoteStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	storage "helloworld-ai/internal/storage"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockNoteStore is a mock of NoteStore interface.
type MockNoteStore struct {
	ctrl     *gomock.Controller
	recorder *MockNoteStoreMockRecorder
	isgomock struct{}
}

// MockNoteStoreMockRecorder is the mock recorder for MockNoteStore.
type MockNoteStoreMockRecorder struct {
	mock *MockNoteStore
}

// NewMockNoteStore creates a new mock instance.
func NewMockNoteStore(ctrl *gomock.Controller) *MockNoteStore {
	mock := &MockNoteStore{ctrl: ctrl}
	mock.recorder = &MockNoteStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNoteStore) EXPECT() *MockNoteStoreMockRecorder {
	return m.recorder
}

// DeleteAll mocks base method.
func (m *MockNoteStore) DeleteAll(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAll", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAll indicates an expected call of DeleteAll.
func (mr *MockNoteStoreMockRecorder) DeleteAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAll", reflect.TypeOf((*MockNoteStore)(nil).DeleteAll), ctx)
}

// GetByVaultAndPath mocks base method.
func (m *MockNoteStore) GetByVaultAndPath(ctx context.Context, vaultID int, relPath string) (*storage.NoteRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByVaultAndPath", ctx, vaultID, relPath)
	ret0, _ := ret[0].(*storage.NoteRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByVaultAndPath indicates an expected call of GetByVaultAndPath.
func (mr *MockNoteStoreMockRecorder) GetByVaultAndPath(ctx, vaultID, relPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByVaultAndPath", reflect.TypeOf((*MockNoteStore)(nil).GetByVaultAndPath), ctx, vaultID, relPath)
}

// Upsert mocks base method.
func (m *MockNoteStore) Upsert(ctx context.Context, note *storage.NoteRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, note)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockNoteStoreMockRecorder) Upsert(ctx, note any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockNoteStore)(nil).Upsert), ctx, note)
}
