// Code generated by MockGen. DO NOT EDIT.
// Source: helloworld-ai/internal/storage (interfaces: ChunkStore)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_chunk_store.go -package=mocks helloworld-ai/internal/storage ChunkStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	storage "helloworld-ai/internal/storage"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockChunkStore is a mock of ChunkStore interface.
type MockChunkStore struct {
	ctrl     *gomock.Controller
	recorder *MockChunkStoreMockRecorder
	isgomock struct{}
}

// MockChunkStoreMockRecorder is the mock recorder for MockChunkStore.
type MockChunkStoreMockRecorder struct {
	mock *MockChunkStore
}

// NewMockChunkStore creates a new mock instance.
func NewMockChunkStore(ctrl *gomock.Controller) *MockChunkStore {
	mock := &MockChunkStore{ctrl: ctrl}
	mock.recorder = &MockChunkStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChunkStore) EXPECT() *MockChunkStoreMockRecorder {
	return m.recorder
}

// DeleteAll mocks base method.
func (m *MockChunkStore) DeleteAll(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAll", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAll indicates an expected call of DeleteAll.
func (mr *MockChunkStoreMockRecorder) DeleteAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAll", reflect.TypeOf((*MockChunkStore)(nil).DeleteAll), ctx)
}

// DeleteByNote mocks base method.
func (m *MockChunkStore) DeleteByNote(ctx context.Context, noteID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByNote", ctx, noteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByNote indicates an expected call of DeleteByNote.
func (mr *MockChunkStoreMockRecorder) DeleteByNote(ctx, noteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByNote", reflect.TypeOf((*MockChunkStore)(nil).DeleteByNote), ctx, noteID)
}

// GetAllIDs mocks base method.
func (m *MockChunkStore) GetAllIDs(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllIDs", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllIDs indicates an expected call of GetAllIDs.
func (mr *MockChunkStoreMockRecorder) GetAllIDs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllIDs", reflect.TypeOf((*MockChunkStore)(nil).GetAllIDs), ctx)
}

// GetByID mocks base method.
func (m *MockChunkStore) GetByID(ctx context.Context, id string) (*storage.ChunkRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*storage.ChunkRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockChunkStoreMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockChunkStore)(nil).GetByID), ctx, id)
}

// Insert mocks base method.
func (m *MockChunkStore) Insert(ctx context.Context, chunk *storage.ChunkRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, chunk)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockChunkStoreMockRecorder) Insert(ctx, chunk any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockChunkStore)(nil).Insert), ctx, chunk)
}

// ListIDsByNote mocks base method.
func (m *MockChunkStore) ListIDsByNote(ctx context.Context, noteID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIDsByNote", ctx, noteID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIDsByNote indicates an expected call of ListIDsByNote.
func (mr *MockChunkStoreMockRecorder) ListIDsByNote(ctx, noteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIDsByNote", reflect.TypeOf((*MockChunkStore)(nil).ListIDsByNote), ctx, noteID)
}
