// Code generated by MockGen. DO NOT EDIT.
// Source: helloworld-ai/internal/storage (interfaces: VaultStore)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_vault_store.go -package=mocks helloworld-ai/internal/storage VaultStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	storage "helloworld-ai/internal/storage"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockVaultStore is a mock of VaultStore interface.
type MockVaultStore struct {
	ctrl     *gomock.Controller
	recorder *MockVaultStoreMockRecorder
	isgomock struct{}
}

// MockVaultStoreMockRecorder is the mock recorder for MockVaultStore.
type MockVaultStoreMockRecorder struct {
	mock *MockVaultStore
}

// NewMockVaultStore creates a new mock instance.
func NewMockVaultStore(ctrl *gomock.Controller) *MockVaultStore {
	mock := &MockVaultStore{ctrl: ctrl}
	mock.recorder = &MockVaultStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVaultStore) EXPECT() *MockVaultStoreMockRecorder {
	return m.recorder
}

// GetOrCreateByName mocks base method.
func (m *MockVaultStore) GetOrCreateByName(ctx context.Context, name, rootPath string) (storage.VaultRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateByName", ctx, name, rootPath)
	ret0, _ := ret[0].(storage.VaultRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreateByName indicates an expected call of GetOrCreateByName.
func (mr *MockVaultStoreMockRecorder) GetOrCreateByName(ctx, name, rootPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateByName", reflect.TypeOf((*MockVaultStore)(nil).GetOrCreateByName), ctx, name, rootPath)
}

// ListAll mocks base method.
func (m *MockVaultStore) ListAll(ctx context.Context) ([]storage.VaultRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", ctx)
	ret0, _ := ret[0].([]storage.VaultRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockVaultStoreMockRecorder) ListAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockVaultStore)(nil).ListAll), ctx)
}
